load("//hello:hello.bzl", "hello", "hello_with_label")
# load("@src//hello:hello.bzl", "hello")

hello(
    name = "hello",
    number = 2,
)

hello_with_label(
    name = "hello_with_label",
    mylabel = "hello",
)
